wordpress:
  # Testing a PR with Okteto Preview
  ## Persistence Parameters
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## @param persistence.enabled Enable persistence using Persistent Volume Claims
    ##
    enabled: true

    ## @param persistence.size Persistent Volume size
    ##
    size: 500Mi

#  podSecurityContext:
#    enabled: false
#
#  containerSecurityContext:
#    enabled: false
  
  service:
    annotations:
      dev.okteto.com/auto-ingress: "true"

  mariadb:
    primary:
      persistence:
        size: 500Mi